### ISSUE TITLE
EXC_GUARD

### ISSUE THREAD

**Issue by zerozhu** [dreese/FastSocket#17]
![2015-07-27 3 46 04](https://cloud.githubusercontent.com/assets/1926639/8900908/ecbc0aec-3476-11e5-946d-7875c1b70c63.png)

my app crashed many times, look at the pic, thank you very much

**Comment by dreese** [comment]
Sorry for the delay. Just saw this.

**Comment by dreese** [comment]
One thing I noticed is that calling connect:0 behaves differently than calling connect:1. Partly, this is because connect:0 calls connect() while connect:1 calls connect_timeout(). connect() appears to create a valid socket that can be close()'d while connect_timeout() does not.

This led to a situation where the socket was closed but not zeroed out. Instead of zeroing the socket descriptor, I ended up modifying the behavior of connect_timeout() so that it behaved like the native connect() method — which does not close the socket after a connection failure.

Once that change was made, the "double-close" failure went away. I was never able to reproduce the crash, but I did find a unit test that was able to verify that my change made the behavior consistent.
